// export const integrationsRoute = (slug = ':slug') => `/proyectos/${slug}/integraciones`;
export const homeRoute = '/';
export const dashboardRoute = '/dashboard';
export const loginRoute = '/login';
export const headquartersRoute = '/sedes';
export const createHeadquartersRoute = '/nueva-sede';
export const teamRoute = '/equipo';
export const createTeamRoute = '/nuevo-colaborador';
export const inventoryRoute = '/inventario';
export const createInventoryRoute = '/nuevo-item';
export const thirdsRoute = '/terceros';
export const createThirdsRoute = '/nueva-entidad';